# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - temp

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Pulling lingoport into develop branch"
        pr_body: "*An automated PR by github actions to sync lingoport & develop*"
